name: Develop Workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  dev_image:
    name: "Build DEV docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to Github Registry
        uses: docker/login-action@v3 
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image latest tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/lamassuiot/lamassu-ui:${{ github.sha }}
            ghcr.io/lamassuiot/lamassu-ui:dev
